import type { Static } from '@feathersjs/typebox';
import type { HookContext } from '../../declarations';
export declare const deviceLockHistorySchema: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TNumber;
    type: import("@sinclair/typebox").TNumber;
    lockedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
    unlockedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
    createdAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    updatedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    deviceId: import("@sinclair/typebox").TInteger;
    loanId: import("@sinclair/typebox").TInteger;
    reason: import("@sinclair/typebox").TString<string>;
    loan: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TNumber;
        accountId: import("@sinclair/typebox").TString<string>;
        firstRepaymentDate: import("@sinclair/typebox").TAny;
        loanName: import("@sinclair/typebox").TString<string>;
        status: import("@sinclair/typebox").TString<string>;
        mambuImei: import("@sinclair/typebox").TString<string>;
        clientId: import("@sinclair/typebox").TInteger;
        client: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TNumber;
            fullName: import("@sinclair/typebox").TString<string>;
            idNumber: import("@sinclair/typebox").TString<string>;
            emailAddress: import("@sinclair/typebox").TString<"email">;
            phoneNumber: import("@sinclair/typebox").TString<string>;
            location: import("@sinclair/typebox").TString<string>;
            status: import("@sinclair/typebox").TNumber;
            createdAt: import("@sinclair/typebox").TString<string>;
            updatedAt: import("@sinclair/typebox").TString<string>;
        }>>;
        createdAt: import("@sinclair/typebox").TString<string>;
        updatedAt: import("@sinclair/typebox").TString<string>;
        retry: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        encodedKey: import("@sinclair/typebox").TString<string>;
        mambuSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        mambuSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<"date-time">>;
        daysRemaining: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        paid: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        paidOff: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        daysToNextInstallment: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    }>>;
    device: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TNumber;
        imei: import("@sinclair/typebox").TString<string>;
        status: import("@sinclair/typebox").TAny;
        loanId: import("@sinclair/typebox").TInteger;
        loan: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TNumber;
            accountId: import("@sinclair/typebox").TString<string>;
            firstRepaymentDate: import("@sinclair/typebox").TAny;
            loanName: import("@sinclair/typebox").TString<string>;
            status: import("@sinclair/typebox").TString<string>;
            mambuImei: import("@sinclair/typebox").TString<string>;
            clientId: import("@sinclair/typebox").TInteger;
            client: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TNumber;
                fullName: import("@sinclair/typebox").TString<string>;
                idNumber: import("@sinclair/typebox").TString<string>;
                emailAddress: import("@sinclair/typebox").TString<"email">;
                phoneNumber: import("@sinclair/typebox").TString<string>;
                location: import("@sinclair/typebox").TString<string>;
                status: import("@sinclair/typebox").TNumber;
                createdAt: import("@sinclair/typebox").TString<string>;
                updatedAt: import("@sinclair/typebox").TString<string>;
            }>>;
            createdAt: import("@sinclair/typebox").TString<string>;
            updatedAt: import("@sinclair/typebox").TString<string>;
            retry: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            encodedKey: import("@sinclair/typebox").TString<string>;
            mambuSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            mambuSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<"date-time">>;
            daysRemaining: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            paid: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            paidOff: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            daysToNextInstallment: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        }>>;
        createdAt: import("@sinclair/typebox").TString<"date-time">;
        updatedAt: import("@sinclair/typebox").TString<"date-time">;
        serialNo: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        make: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        locked: import("@sinclair/typebox").TBoolean;
        mambuSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        mambuSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        nuovoSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        nuovoSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        clientId: import("@sinclair/typebox").TInteger;
        client: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TNumber;
            fullName: import("@sinclair/typebox").TString<string>;
            idNumber: import("@sinclair/typebox").TString<string>;
            emailAddress: import("@sinclair/typebox").TString<"email">;
            phoneNumber: import("@sinclair/typebox").TString<string>;
            location: import("@sinclair/typebox").TString<string>;
            status: import("@sinclair/typebox").TNumber;
            createdAt: import("@sinclair/typebox").TString<string>;
            updatedAt: import("@sinclair/typebox").TString<string>;
        }>>;
        nuovoDeviceId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        lockReady: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        lockReadyScheduleAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        lockDateSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        nextLockDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        initialLockDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        lastConnectedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        reminderSet: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        reminderSetDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        scheduleNumber: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    }>>;
}>;
export type DeviceLockHistory = Static<typeof deviceLockHistorySchema>;
export declare const deviceLockHistoryValidator: import("@feathersjs/schema").Validator<any, any>;
export declare const deviceLockHistoryResolver: import("@feathersjs/schema").Resolver<{
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    lockedAt?: any;
    unlockedAt?: any;
    type: number;
    reason: string;
    id: number;
    device: {
        mambuSynced?: boolean | undefined;
        mambuSyncedAt?: any;
        serialNo?: any;
        make?: any;
        model?: any;
        nuovoSynced?: boolean | undefined;
        nuovoSyncedAt?: any;
        nuovoDeviceId?: any;
        lockReady?: boolean | undefined;
        lockReadyScheduleAt?: any;
        lockDateSynced?: boolean | undefined;
        nextLockDate?: any;
        initialLockDate?: any;
        lastConnectedAt?: any;
        reminderSet?: boolean | undefined;
        reminderSetDate?: any;
        scheduleNumber?: number | undefined;
        id: number;
        status: any;
        client: {
            location: string;
            id: number;
            status: number;
            fullName: string;
            idNumber: string;
            emailAddress: string;
            phoneNumber: string;
            createdAt: string;
            updatedAt: string;
        };
        loan: {
            retry?: number | undefined;
            mambuSynced?: boolean | undefined;
            mambuSyncedAt?: string | undefined;
            daysRemaining?: number | undefined;
            paid?: boolean | undefined;
            paidOff?: boolean | undefined;
            daysToNextInstallment?: number | undefined;
            id: number;
            status: string;
            client: {
                location: string;
                id: number;
                status: number;
                fullName: string;
                idNumber: string;
                emailAddress: string;
                phoneNumber: string;
                createdAt: string;
                updatedAt: string;
            };
            createdAt: string;
            updatedAt: string;
            accountId: string;
            firstRepaymentDate: any;
            loanName: string;
            mambuImei: string;
            clientId: number;
            encodedKey: string;
        };
        imei: string;
        createdAt: string;
        updatedAt: string;
        loanId: number;
        clientId: number;
        locked: boolean;
    };
    loan: {
        retry?: number | undefined;
        mambuSynced?: boolean | undefined;
        mambuSyncedAt?: string | undefined;
        daysRemaining?: number | undefined;
        paid?: boolean | undefined;
        paidOff?: boolean | undefined;
        daysToNextInstallment?: number | undefined;
        id: number;
        status: string;
        client: {
            location: string;
            id: number;
            status: number;
            fullName: string;
            idNumber: string;
            emailAddress: string;
            phoneNumber: string;
            createdAt: string;
            updatedAt: string;
        };
        createdAt: string;
        updatedAt: string;
        accountId: string;
        firstRepaymentDate: any;
        loanName: string;
        mambuImei: string;
        clientId: number;
        encodedKey: string;
    };
    deviceId: number;
    loanId: number;
}, HookContext>;
export declare const deviceLockHistoryExternalResolver: import("@feathersjs/schema").Resolver<{
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    lockedAt?: any;
    unlockedAt?: any;
    type: number;
    reason: string;
    id: number;
    device: {
        mambuSynced?: boolean | undefined;
        mambuSyncedAt?: any;
        serialNo?: any;
        make?: any;
        model?: any;
        nuovoSynced?: boolean | undefined;
        nuovoSyncedAt?: any;
        nuovoDeviceId?: any;
        lockReady?: boolean | undefined;
        lockReadyScheduleAt?: any;
        lockDateSynced?: boolean | undefined;
        nextLockDate?: any;
        initialLockDate?: any;
        lastConnectedAt?: any;
        reminderSet?: boolean | undefined;
        reminderSetDate?: any;
        scheduleNumber?: number | undefined;
        id: number;
        status: any;
        client: {
            location: string;
            id: number;
            status: number;
            fullName: string;
            idNumber: string;
            emailAddress: string;
            phoneNumber: string;
            createdAt: string;
            updatedAt: string;
        };
        loan: {
            retry?: number | undefined;
            mambuSynced?: boolean | undefined;
            mambuSyncedAt?: string | undefined;
            daysRemaining?: number | undefined;
            paid?: boolean | undefined;
            paidOff?: boolean | undefined;
            daysToNextInstallment?: number | undefined;
            id: number;
            status: string;
            client: {
                location: string;
                id: number;
                status: number;
                fullName: string;
                idNumber: string;
                emailAddress: string;
                phoneNumber: string;
                createdAt: string;
                updatedAt: string;
            };
            createdAt: string;
            updatedAt: string;
            accountId: string;
            firstRepaymentDate: any;
            loanName: string;
            mambuImei: string;
            clientId: number;
            encodedKey: string;
        };
        imei: string;
        createdAt: string;
        updatedAt: string;
        loanId: number;
        clientId: number;
        locked: boolean;
    };
    loan: {
        retry?: number | undefined;
        mambuSynced?: boolean | undefined;
        mambuSyncedAt?: string | undefined;
        daysRemaining?: number | undefined;
        paid?: boolean | undefined;
        paidOff?: boolean | undefined;
        daysToNextInstallment?: number | undefined;
        id: number;
        status: string;
        client: {
            location: string;
            id: number;
            status: number;
            fullName: string;
            idNumber: string;
            emailAddress: string;
            phoneNumber: string;
            createdAt: string;
            updatedAt: string;
        };
        createdAt: string;
        updatedAt: string;
        accountId: string;
        firstRepaymentDate: any;
        loanName: string;
        mambuImei: string;
        clientId: number;
        encodedKey: string;
    };
    deviceId: number;
    loanId: number;
}, HookContext>;
export declare const deviceLockHistoryDataSchema: import("@sinclair/typebox").TPick<import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TNumber;
    type: import("@sinclair/typebox").TNumber;
    lockedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
    unlockedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
    createdAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    updatedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    deviceId: import("@sinclair/typebox").TInteger;
    loanId: import("@sinclair/typebox").TInteger;
    reason: import("@sinclair/typebox").TString<string>;
    loan: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TNumber;
        accountId: import("@sinclair/typebox").TString<string>;
        firstRepaymentDate: import("@sinclair/typebox").TAny;
        loanName: import("@sinclair/typebox").TString<string>;
        status: import("@sinclair/typebox").TString<string>;
        mambuImei: import("@sinclair/typebox").TString<string>;
        clientId: import("@sinclair/typebox").TInteger;
        client: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TNumber;
            fullName: import("@sinclair/typebox").TString<string>;
            idNumber: import("@sinclair/typebox").TString<string>;
            emailAddress: import("@sinclair/typebox").TString<"email">;
            phoneNumber: import("@sinclair/typebox").TString<string>;
            location: import("@sinclair/typebox").TString<string>;
            status: import("@sinclair/typebox").TNumber;
            createdAt: import("@sinclair/typebox").TString<string>;
            updatedAt: import("@sinclair/typebox").TString<string>;
        }>>;
        createdAt: import("@sinclair/typebox").TString<string>;
        updatedAt: import("@sinclair/typebox").TString<string>;
        retry: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        encodedKey: import("@sinclair/typebox").TString<string>;
        mambuSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        mambuSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<"date-time">>;
        daysRemaining: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        paid: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        paidOff: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        daysToNextInstallment: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    }>>;
    device: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TNumber;
        imei: import("@sinclair/typebox").TString<string>;
        status: import("@sinclair/typebox").TAny;
        loanId: import("@sinclair/typebox").TInteger;
        loan: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TNumber;
            accountId: import("@sinclair/typebox").TString<string>;
            firstRepaymentDate: import("@sinclair/typebox").TAny;
            loanName: import("@sinclair/typebox").TString<string>;
            status: import("@sinclair/typebox").TString<string>;
            mambuImei: import("@sinclair/typebox").TString<string>;
            clientId: import("@sinclair/typebox").TInteger;
            client: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TNumber;
                fullName: import("@sinclair/typebox").TString<string>;
                idNumber: import("@sinclair/typebox").TString<string>;
                emailAddress: import("@sinclair/typebox").TString<"email">;
                phoneNumber: import("@sinclair/typebox").TString<string>;
                location: import("@sinclair/typebox").TString<string>;
                status: import("@sinclair/typebox").TNumber;
                createdAt: import("@sinclair/typebox").TString<string>;
                updatedAt: import("@sinclair/typebox").TString<string>;
            }>>;
            createdAt: import("@sinclair/typebox").TString<string>;
            updatedAt: import("@sinclair/typebox").TString<string>;
            retry: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            encodedKey: import("@sinclair/typebox").TString<string>;
            mambuSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            mambuSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<"date-time">>;
            daysRemaining: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            paid: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            paidOff: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            daysToNextInstallment: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        }>>;
        createdAt: import("@sinclair/typebox").TString<"date-time">;
        updatedAt: import("@sinclair/typebox").TString<"date-time">;
        serialNo: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        make: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        locked: import("@sinclair/typebox").TBoolean;
        mambuSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        mambuSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        nuovoSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        nuovoSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        clientId: import("@sinclair/typebox").TInteger;
        client: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TNumber;
            fullName: import("@sinclair/typebox").TString<string>;
            idNumber: import("@sinclair/typebox").TString<string>;
            emailAddress: import("@sinclair/typebox").TString<"email">;
            phoneNumber: import("@sinclair/typebox").TString<string>;
            location: import("@sinclair/typebox").TString<string>;
            status: import("@sinclair/typebox").TNumber;
            createdAt: import("@sinclair/typebox").TString<string>;
            updatedAt: import("@sinclair/typebox").TString<string>;
        }>>;
        nuovoDeviceId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        lockReady: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        lockReadyScheduleAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        lockDateSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        nextLockDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        initialLockDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        lastConnectedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        reminderSet: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        reminderSetDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        scheduleNumber: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    }>>;
}>, ["type", "lockedAt", "unlockedAt", "createdAt", "updatedAt", "deviceId", "loanId", "reason"]>;
export type DeviceLockHistoryData = Static<typeof deviceLockHistoryDataSchema>;
export declare const deviceLockHistoryDataValidator: import("@feathersjs/schema").Validator<any, any>;
export declare const deviceLockHistoryDataResolver: import("@feathersjs/schema").Resolver<{
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    lockedAt?: any;
    unlockedAt?: any;
    type: number;
    reason: string;
    id: number;
    device: {
        mambuSynced?: boolean | undefined;
        mambuSyncedAt?: any;
        serialNo?: any;
        make?: any;
        model?: any;
        nuovoSynced?: boolean | undefined;
        nuovoSyncedAt?: any;
        nuovoDeviceId?: any;
        lockReady?: boolean | undefined;
        lockReadyScheduleAt?: any;
        lockDateSynced?: boolean | undefined;
        nextLockDate?: any;
        initialLockDate?: any;
        lastConnectedAt?: any;
        reminderSet?: boolean | undefined;
        reminderSetDate?: any;
        scheduleNumber?: number | undefined;
        id: number;
        status: any;
        client: {
            location: string;
            id: number;
            status: number;
            fullName: string;
            idNumber: string;
            emailAddress: string;
            phoneNumber: string;
            createdAt: string;
            updatedAt: string;
        };
        loan: {
            retry?: number | undefined;
            mambuSynced?: boolean | undefined;
            mambuSyncedAt?: string | undefined;
            daysRemaining?: number | undefined;
            paid?: boolean | undefined;
            paidOff?: boolean | undefined;
            daysToNextInstallment?: number | undefined;
            id: number;
            status: string;
            client: {
                location: string;
                id: number;
                status: number;
                fullName: string;
                idNumber: string;
                emailAddress: string;
                phoneNumber: string;
                createdAt: string;
                updatedAt: string;
            };
            createdAt: string;
            updatedAt: string;
            accountId: string;
            firstRepaymentDate: any;
            loanName: string;
            mambuImei: string;
            clientId: number;
            encodedKey: string;
        };
        imei: string;
        createdAt: string;
        updatedAt: string;
        loanId: number;
        clientId: number;
        locked: boolean;
    };
    loan: {
        retry?: number | undefined;
        mambuSynced?: boolean | undefined;
        mambuSyncedAt?: string | undefined;
        daysRemaining?: number | undefined;
        paid?: boolean | undefined;
        paidOff?: boolean | undefined;
        daysToNextInstallment?: number | undefined;
        id: number;
        status: string;
        client: {
            location: string;
            id: number;
            status: number;
            fullName: string;
            idNumber: string;
            emailAddress: string;
            phoneNumber: string;
            createdAt: string;
            updatedAt: string;
        };
        createdAt: string;
        updatedAt: string;
        accountId: string;
        firstRepaymentDate: any;
        loanName: string;
        mambuImei: string;
        clientId: number;
        encodedKey: string;
    };
    deviceId: number;
    loanId: number;
}, HookContext>;
export declare const deviceLockHistoryPatchSchema: import("@sinclair/typebox").TPartial<import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TNumber;
    type: import("@sinclair/typebox").TNumber;
    lockedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
    unlockedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
    createdAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    updatedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    deviceId: import("@sinclair/typebox").TInteger;
    loanId: import("@sinclair/typebox").TInteger;
    reason: import("@sinclair/typebox").TString<string>;
    loan: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TNumber;
        accountId: import("@sinclair/typebox").TString<string>;
        firstRepaymentDate: import("@sinclair/typebox").TAny;
        loanName: import("@sinclair/typebox").TString<string>;
        status: import("@sinclair/typebox").TString<string>;
        mambuImei: import("@sinclair/typebox").TString<string>;
        clientId: import("@sinclair/typebox").TInteger;
        client: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TNumber;
            fullName: import("@sinclair/typebox").TString<string>;
            idNumber: import("@sinclair/typebox").TString<string>;
            emailAddress: import("@sinclair/typebox").TString<"email">;
            phoneNumber: import("@sinclair/typebox").TString<string>;
            location: import("@sinclair/typebox").TString<string>;
            status: import("@sinclair/typebox").TNumber;
            createdAt: import("@sinclair/typebox").TString<string>;
            updatedAt: import("@sinclair/typebox").TString<string>;
        }>>;
        createdAt: import("@sinclair/typebox").TString<string>;
        updatedAt: import("@sinclair/typebox").TString<string>;
        retry: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        encodedKey: import("@sinclair/typebox").TString<string>;
        mambuSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        mambuSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<"date-time">>;
        daysRemaining: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        paid: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        paidOff: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        daysToNextInstallment: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    }>>;
    device: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TNumber;
        imei: import("@sinclair/typebox").TString<string>;
        status: import("@sinclair/typebox").TAny;
        loanId: import("@sinclair/typebox").TInteger;
        loan: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TNumber;
            accountId: import("@sinclair/typebox").TString<string>;
            firstRepaymentDate: import("@sinclair/typebox").TAny;
            loanName: import("@sinclair/typebox").TString<string>;
            status: import("@sinclair/typebox").TString<string>;
            mambuImei: import("@sinclair/typebox").TString<string>;
            clientId: import("@sinclair/typebox").TInteger;
            client: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TNumber;
                fullName: import("@sinclair/typebox").TString<string>;
                idNumber: import("@sinclair/typebox").TString<string>;
                emailAddress: import("@sinclair/typebox").TString<"email">;
                phoneNumber: import("@sinclair/typebox").TString<string>;
                location: import("@sinclair/typebox").TString<string>;
                status: import("@sinclair/typebox").TNumber;
                createdAt: import("@sinclair/typebox").TString<string>;
                updatedAt: import("@sinclair/typebox").TString<string>;
            }>>;
            createdAt: import("@sinclair/typebox").TString<string>;
            updatedAt: import("@sinclair/typebox").TString<string>;
            retry: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            encodedKey: import("@sinclair/typebox").TString<string>;
            mambuSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            mambuSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<"date-time">>;
            daysRemaining: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            paid: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            paidOff: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            daysToNextInstallment: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        }>>;
        createdAt: import("@sinclair/typebox").TString<"date-time">;
        updatedAt: import("@sinclair/typebox").TString<"date-time">;
        serialNo: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        make: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        locked: import("@sinclair/typebox").TBoolean;
        mambuSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        mambuSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        nuovoSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        nuovoSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        clientId: import("@sinclair/typebox").TInteger;
        client: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TNumber;
            fullName: import("@sinclair/typebox").TString<string>;
            idNumber: import("@sinclair/typebox").TString<string>;
            emailAddress: import("@sinclair/typebox").TString<"email">;
            phoneNumber: import("@sinclair/typebox").TString<string>;
            location: import("@sinclair/typebox").TString<string>;
            status: import("@sinclair/typebox").TNumber;
            createdAt: import("@sinclair/typebox").TString<string>;
            updatedAt: import("@sinclair/typebox").TString<string>;
        }>>;
        nuovoDeviceId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        lockReady: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        lockReadyScheduleAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        lockDateSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        nextLockDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        initialLockDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        lastConnectedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        reminderSet: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        reminderSetDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        scheduleNumber: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    }>>;
}>>;
export type DeviceLockHistoryPatch = Static<typeof deviceLockHistoryPatchSchema>;
export declare const deviceLockHistoryPatchValidator: import("@feathersjs/schema").Validator<any, any>;
export declare const deviceLockHistoryPatchResolver: import("@feathersjs/schema").Resolver<{
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    lockedAt?: any;
    unlockedAt?: any;
    type: number;
    reason: string;
    id: number;
    device: {
        mambuSynced?: boolean | undefined;
        mambuSyncedAt?: any;
        serialNo?: any;
        make?: any;
        model?: any;
        nuovoSynced?: boolean | undefined;
        nuovoSyncedAt?: any;
        nuovoDeviceId?: any;
        lockReady?: boolean | undefined;
        lockReadyScheduleAt?: any;
        lockDateSynced?: boolean | undefined;
        nextLockDate?: any;
        initialLockDate?: any;
        lastConnectedAt?: any;
        reminderSet?: boolean | undefined;
        reminderSetDate?: any;
        scheduleNumber?: number | undefined;
        id: number;
        status: any;
        client: {
            location: string;
            id: number;
            status: number;
            fullName: string;
            idNumber: string;
            emailAddress: string;
            phoneNumber: string;
            createdAt: string;
            updatedAt: string;
        };
        loan: {
            retry?: number | undefined;
            mambuSynced?: boolean | undefined;
            mambuSyncedAt?: string | undefined;
            daysRemaining?: number | undefined;
            paid?: boolean | undefined;
            paidOff?: boolean | undefined;
            daysToNextInstallment?: number | undefined;
            id: number;
            status: string;
            client: {
                location: string;
                id: number;
                status: number;
                fullName: string;
                idNumber: string;
                emailAddress: string;
                phoneNumber: string;
                createdAt: string;
                updatedAt: string;
            };
            createdAt: string;
            updatedAt: string;
            accountId: string;
            firstRepaymentDate: any;
            loanName: string;
            mambuImei: string;
            clientId: number;
            encodedKey: string;
        };
        imei: string;
        createdAt: string;
        updatedAt: string;
        loanId: number;
        clientId: number;
        locked: boolean;
    };
    loan: {
        retry?: number | undefined;
        mambuSynced?: boolean | undefined;
        mambuSyncedAt?: string | undefined;
        daysRemaining?: number | undefined;
        paid?: boolean | undefined;
        paidOff?: boolean | undefined;
        daysToNextInstallment?: number | undefined;
        id: number;
        status: string;
        client: {
            location: string;
            id: number;
            status: number;
            fullName: string;
            idNumber: string;
            emailAddress: string;
            phoneNumber: string;
            createdAt: string;
            updatedAt: string;
        };
        createdAt: string;
        updatedAt: string;
        accountId: string;
        firstRepaymentDate: any;
        loanName: string;
        mambuImei: string;
        clientId: number;
        encodedKey: string;
    };
    deviceId: number;
    loanId: number;
}, HookContext>;
export declare const deviceLockHistoryQueryProperties: import("@sinclair/typebox").TPick<import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TNumber;
    type: import("@sinclair/typebox").TNumber;
    lockedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
    unlockedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
    createdAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    updatedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    deviceId: import("@sinclair/typebox").TInteger;
    loanId: import("@sinclair/typebox").TInteger;
    reason: import("@sinclair/typebox").TString<string>;
    loan: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TNumber;
        accountId: import("@sinclair/typebox").TString<string>;
        firstRepaymentDate: import("@sinclair/typebox").TAny;
        loanName: import("@sinclair/typebox").TString<string>;
        status: import("@sinclair/typebox").TString<string>;
        mambuImei: import("@sinclair/typebox").TString<string>;
        clientId: import("@sinclair/typebox").TInteger;
        client: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TNumber;
            fullName: import("@sinclair/typebox").TString<string>;
            idNumber: import("@sinclair/typebox").TString<string>;
            emailAddress: import("@sinclair/typebox").TString<"email">;
            phoneNumber: import("@sinclair/typebox").TString<string>;
            location: import("@sinclair/typebox").TString<string>;
            status: import("@sinclair/typebox").TNumber;
            createdAt: import("@sinclair/typebox").TString<string>;
            updatedAt: import("@sinclair/typebox").TString<string>;
        }>>;
        createdAt: import("@sinclair/typebox").TString<string>;
        updatedAt: import("@sinclair/typebox").TString<string>;
        retry: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        encodedKey: import("@sinclair/typebox").TString<string>;
        mambuSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        mambuSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<"date-time">>;
        daysRemaining: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        paid: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        paidOff: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        daysToNextInstallment: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    }>>;
    device: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TNumber;
        imei: import("@sinclair/typebox").TString<string>;
        status: import("@sinclair/typebox").TAny;
        loanId: import("@sinclair/typebox").TInteger;
        loan: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TNumber;
            accountId: import("@sinclair/typebox").TString<string>;
            firstRepaymentDate: import("@sinclair/typebox").TAny;
            loanName: import("@sinclair/typebox").TString<string>;
            status: import("@sinclair/typebox").TString<string>;
            mambuImei: import("@sinclair/typebox").TString<string>;
            clientId: import("@sinclair/typebox").TInteger;
            client: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TNumber;
                fullName: import("@sinclair/typebox").TString<string>;
                idNumber: import("@sinclair/typebox").TString<string>;
                emailAddress: import("@sinclair/typebox").TString<"email">;
                phoneNumber: import("@sinclair/typebox").TString<string>;
                location: import("@sinclair/typebox").TString<string>;
                status: import("@sinclair/typebox").TNumber;
                createdAt: import("@sinclair/typebox").TString<string>;
                updatedAt: import("@sinclair/typebox").TString<string>;
            }>>;
            createdAt: import("@sinclair/typebox").TString<string>;
            updatedAt: import("@sinclair/typebox").TString<string>;
            retry: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            encodedKey: import("@sinclair/typebox").TString<string>;
            mambuSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            mambuSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<"date-time">>;
            daysRemaining: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            paid: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            paidOff: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            daysToNextInstallment: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        }>>;
        createdAt: import("@sinclair/typebox").TString<"date-time">;
        updatedAt: import("@sinclair/typebox").TString<"date-time">;
        serialNo: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        make: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        locked: import("@sinclair/typebox").TBoolean;
        mambuSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        mambuSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        nuovoSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        nuovoSyncedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        clientId: import("@sinclair/typebox").TInteger;
        client: import("@sinclair/typebox").TRef<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TNumber;
            fullName: import("@sinclair/typebox").TString<string>;
            idNumber: import("@sinclair/typebox").TString<string>;
            emailAddress: import("@sinclair/typebox").TString<"email">;
            phoneNumber: import("@sinclair/typebox").TString<string>;
            location: import("@sinclair/typebox").TString<string>;
            status: import("@sinclair/typebox").TNumber;
            createdAt: import("@sinclair/typebox").TString<string>;
            updatedAt: import("@sinclair/typebox").TString<string>;
        }>>;
        nuovoDeviceId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        lockReady: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        lockReadyScheduleAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        lockDateSynced: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        nextLockDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        initialLockDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        lastConnectedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        reminderSet: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        reminderSetDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
        scheduleNumber: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    }>>;
}>, ["id", "type"]>;
export declare const deviceLockHistoryQuerySchema: import("@sinclair/typebox").TIntersect<[import("@sinclair/typebox").TIntersect<[import("@sinclair/typebox").TPartial<import("@sinclair/typebox").TObject<{
    $limit: import("@sinclair/typebox").TNumber;
    $skip: import("@sinclair/typebox").TNumber;
    $sort: import("@sinclair/typebox").TObject<{
        type: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    }>;
    $select: import("@sinclair/typebox").TUnsafe<("type" | "id")[]>;
    $and: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        type: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TPartial<import("@sinclair/typebox").TIntersect<[import("@sinclair/typebox").TObject<{
            $gt: import("@sinclair/typebox").TNumber;
            $gte: import("@sinclair/typebox").TNumber;
            $lt: import("@sinclair/typebox").TNumber;
            $lte: import("@sinclair/typebox").TNumber;
            $ne: import("@sinclair/typebox").TNumber;
            $in: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
            $nin: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
        }>, import("@sinclair/typebox").TObject<{
            [key: string]: import("@sinclair/typebox").TSchema;
        } | undefined>]>>]>>;
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TPartial<import("@sinclair/typebox").TIntersect<[import("@sinclair/typebox").TObject<{
            $gt: import("@sinclair/typebox").TNumber;
            $gte: import("@sinclair/typebox").TNumber;
            $lt: import("@sinclair/typebox").TNumber;
            $lte: import("@sinclair/typebox").TNumber;
            $ne: import("@sinclair/typebox").TNumber;
            $in: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
            $nin: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
        }>, import("@sinclair/typebox").TObject<{
            [key: string]: import("@sinclair/typebox").TSchema;
        } | undefined>]>>]>>;
    }>>, import("@sinclair/typebox").TObject<{
        $or: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            type: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TPartial<import("@sinclair/typebox").TIntersect<[import("@sinclair/typebox").TObject<{
                $gt: import("@sinclair/typebox").TNumber;
                $gte: import("@sinclair/typebox").TNumber;
                $lt: import("@sinclair/typebox").TNumber;
                $lte: import("@sinclair/typebox").TNumber;
                $ne: import("@sinclair/typebox").TNumber;
                $in: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
                $nin: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
            }>, import("@sinclair/typebox").TObject<{
                [key: string]: import("@sinclair/typebox").TSchema;
            } | undefined>]>>]>>;
            id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TPartial<import("@sinclair/typebox").TIntersect<[import("@sinclair/typebox").TObject<{
                $gt: import("@sinclair/typebox").TNumber;
                $gte: import("@sinclair/typebox").TNumber;
                $lt: import("@sinclair/typebox").TNumber;
                $lte: import("@sinclair/typebox").TNumber;
                $ne: import("@sinclair/typebox").TNumber;
                $in: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
                $nin: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
            }>, import("@sinclair/typebox").TObject<{
                [key: string]: import("@sinclair/typebox").TSchema;
            } | undefined>]>>]>>;
        }>>>;
    }>]>>;
    $or: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        type: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TPartial<import("@sinclair/typebox").TIntersect<[import("@sinclair/typebox").TObject<{
            $gt: import("@sinclair/typebox").TNumber;
            $gte: import("@sinclair/typebox").TNumber;
            $lt: import("@sinclair/typebox").TNumber;
            $lte: import("@sinclair/typebox").TNumber;
            $ne: import("@sinclair/typebox").TNumber;
            $in: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
            $nin: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
        }>, import("@sinclair/typebox").TObject<{
            [key: string]: import("@sinclair/typebox").TSchema;
        } | undefined>]>>]>>;
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TPartial<import("@sinclair/typebox").TIntersect<[import("@sinclair/typebox").TObject<{
            $gt: import("@sinclair/typebox").TNumber;
            $gte: import("@sinclair/typebox").TNumber;
            $lt: import("@sinclair/typebox").TNumber;
            $lte: import("@sinclair/typebox").TNumber;
            $ne: import("@sinclair/typebox").TNumber;
            $in: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
            $nin: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
        }>, import("@sinclair/typebox").TObject<{
            [key: string]: import("@sinclair/typebox").TSchema;
        } | undefined>]>>]>>;
    }>>>;
}>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
    type: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TPartial<import("@sinclair/typebox").TIntersect<[import("@sinclair/typebox").TObject<{
        $gt: import("@sinclair/typebox").TNumber;
        $gte: import("@sinclair/typebox").TNumber;
        $lt: import("@sinclair/typebox").TNumber;
        $lte: import("@sinclair/typebox").TNumber;
        $ne: import("@sinclair/typebox").TNumber;
        $in: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
        $nin: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
    }>, import("@sinclair/typebox").TObject<{
        [key: string]: import("@sinclair/typebox").TSchema;
    } | undefined>]>>]>>;
    id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TPartial<import("@sinclair/typebox").TIntersect<[import("@sinclair/typebox").TObject<{
        $gt: import("@sinclair/typebox").TNumber;
        $gte: import("@sinclair/typebox").TNumber;
        $lt: import("@sinclair/typebox").TNumber;
        $lte: import("@sinclair/typebox").TNumber;
        $ne: import("@sinclair/typebox").TNumber;
        $in: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
        $nin: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TNumber>;
    }>, import("@sinclair/typebox").TObject<{
        [key: string]: import("@sinclair/typebox").TSchema;
    } | undefined>]>>]>>;
}>>]>, import("@sinclair/typebox").TObject<{}>]>;
export declare const lockHistoryResultResolver: import("@feathersjs/schema").Resolver<{
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    lockedAt?: any;
    unlockedAt?: any;
    type: number;
    reason: string;
    id: number;
    device: {
        mambuSynced?: boolean | undefined;
        mambuSyncedAt?: any;
        serialNo?: any;
        make?: any;
        model?: any;
        nuovoSynced?: boolean | undefined;
        nuovoSyncedAt?: any;
        nuovoDeviceId?: any;
        lockReady?: boolean | undefined;
        lockReadyScheduleAt?: any;
        lockDateSynced?: boolean | undefined;
        nextLockDate?: any;
        initialLockDate?: any;
        lastConnectedAt?: any;
        reminderSet?: boolean | undefined;
        reminderSetDate?: any;
        scheduleNumber?: number | undefined;
        id: number;
        status: any;
        client: {
            location: string;
            id: number;
            status: number;
            fullName: string;
            idNumber: string;
            emailAddress: string;
            phoneNumber: string;
            createdAt: string;
            updatedAt: string;
        };
        loan: {
            retry?: number | undefined;
            mambuSynced?: boolean | undefined;
            mambuSyncedAt?: string | undefined;
            daysRemaining?: number | undefined;
            paid?: boolean | undefined;
            paidOff?: boolean | undefined;
            daysToNextInstallment?: number | undefined;
            id: number;
            status: string;
            client: {
                location: string;
                id: number;
                status: number;
                fullName: string;
                idNumber: string;
                emailAddress: string;
                phoneNumber: string;
                createdAt: string;
                updatedAt: string;
            };
            createdAt: string;
            updatedAt: string;
            accountId: string;
            firstRepaymentDate: any;
            loanName: string;
            mambuImei: string;
            clientId: number;
            encodedKey: string;
        };
        imei: string;
        createdAt: string;
        updatedAt: string;
        loanId: number;
        clientId: number;
        locked: boolean;
    };
    loan: {
        retry?: number | undefined;
        mambuSynced?: boolean | undefined;
        mambuSyncedAt?: string | undefined;
        daysRemaining?: number | undefined;
        paid?: boolean | undefined;
        paidOff?: boolean | undefined;
        daysToNextInstallment?: number | undefined;
        id: number;
        status: string;
        client: {
            location: string;
            id: number;
            status: number;
            fullName: string;
            idNumber: string;
            emailAddress: string;
            phoneNumber: string;
            createdAt: string;
            updatedAt: string;
        };
        createdAt: string;
        updatedAt: string;
        accountId: string;
        firstRepaymentDate: any;
        loanName: string;
        mambuImei: string;
        clientId: number;
        encodedKey: string;
    };
    deviceId: number;
    loanId: number;
}, HookContext>;
export type DeviceLockHistoryQuery = Static<typeof deviceLockHistoryQuerySchema>;
export declare const deviceLockHistoryQueryValidator: import("@feathersjs/schema").Validator<any, any>;
export declare const deviceLockHistoryQueryResolver: import("@feathersjs/schema").Resolver<Partial<{
    $limit: number;
    $skip: number;
    $sort: {
        type?: number | undefined;
        id?: number | undefined;
    };
    $select: ("type" | "id")[];
    $and: ({
        type?: number | Partial<{
            $gt: number;
            $gte: number;
            $lt: number;
            $lte: number;
            $ne: number;
            $in: number[];
            $nin: number[];
        } & {}> | undefined;
        id?: number | Partial<{
            $gt: number;
            $gte: number;
            $lt: number;
            $lte: number;
            $ne: number;
            $in: number[];
            $nin: number[];
        } & {}> | undefined;
    } | {
        $or: {
            type?: number | Partial<{
                $gt: number;
                $gte: number;
                $lt: number;
                $lte: number;
                $ne: number;
                $in: number[];
                $nin: number[];
            } & {}> | undefined;
            id?: number | Partial<{
                $gt: number;
                $gte: number;
                $lt: number;
                $lte: number;
                $ne: number;
                $in: number[];
                $nin: number[];
            } & {}> | undefined;
        }[];
    })[];
    $or: {
        type?: number | Partial<{
            $gt: number;
            $gte: number;
            $lt: number;
            $lte: number;
            $ne: number;
            $in: number[];
            $nin: number[];
        } & {}> | undefined;
        id?: number | Partial<{
            $gt: number;
            $gte: number;
            $lt: number;
            $lte: number;
            $ne: number;
            $in: number[];
            $nin: number[];
        } & {}> | undefined;
    }[];
}> & {
    type?: number | Partial<{
        $gt: number;
        $gte: number;
        $lt: number;
        $lte: number;
        $ne: number;
        $in: number[];
        $nin: number[];
    } & {}> | undefined;
    id?: number | Partial<{
        $gt: number;
        $gte: number;
        $lt: number;
        $lte: number;
        $ne: number;
        $in: number[];
        $nin: number[];
    } & {}> | undefined;
} & {}, HookContext>;
