import { Device } from '../../client';
import { Application } from '../../declarations';
export declare class LockDevice {
    private app;
    constructor(app: Application);
    fetchAllPendingLocks(): Promise<{
        mambuSynced?: boolean | undefined;
        mambuSyncedAt?: any;
        serialNo?: any;
        make?: any;
        model?: any;
        nuovoSynced?: boolean | undefined;
        nuovoSyncedAt?: any;
        nuovoDeviceId?: any;
        lockReady?: boolean | undefined;
        lockReadyScheduleAt?: any;
        lockDateSynced?: boolean | undefined;
        nextLockDate?: any;
        initialLockDate?: any;
        lastConnectedAt?: any;
        reminderSet?: boolean | undefined;
        reminderSetDate?: any;
        scheduleNumber?: number | undefined;
        id: number;
        status: any;
        client: {
            location: string;
            id: number;
            status: number;
            fullName: string;
            idNumber: string;
            emailAddress: string;
            phoneNumber: string;
            createdAt: string;
            updatedAt: string;
        };
        loan: {
            retry?: number | undefined;
            mambuSynced?: boolean | undefined;
            mambuSyncedAt?: string | undefined;
            daysRemaining?: number | undefined;
            paid?: boolean | undefined;
            paidOff?: boolean | undefined;
            daysToNextInstallment?: number | undefined;
            id: number;
            status: string;
            client: {
                location: string;
                id: number;
                status: number;
                fullName: string;
                idNumber: string;
                emailAddress: string;
                phoneNumber: string;
                createdAt: string;
                updatedAt: string;
            };
            createdAt: string;
            updatedAt: string;
            accountId: string;
            firstRepaymentDate: any;
            loanName: string;
            mambuImei: string;
            clientId: number;
            encodedKey: string;
        };
        imei: string;
        createdAt: string;
        updatedAt: string;
        loanId: number;
        clientId: number;
        locked: boolean;
    }[]>;
    fetchLockedDevices(): Promise<{
        mambuSynced?: boolean | undefined;
        mambuSyncedAt?: any;
        serialNo?: any;
        make?: any;
        model?: any;
        nuovoSynced?: boolean | undefined;
        nuovoSyncedAt?: any;
        nuovoDeviceId?: any;
        lockReady?: boolean | undefined;
        lockReadyScheduleAt?: any;
        lockDateSynced?: boolean | undefined;
        nextLockDate?: any;
        initialLockDate?: any;
        lastConnectedAt?: any;
        reminderSet?: boolean | undefined;
        reminderSetDate?: any;
        scheduleNumber?: number | undefined;
        id: number;
        status: any;
        client: {
            location: string;
            id: number;
            status: number;
            fullName: string;
            idNumber: string;
            emailAddress: string;
            phoneNumber: string;
            createdAt: string;
            updatedAt: string;
        };
        loan: {
            retry?: number | undefined;
            mambuSynced?: boolean | undefined;
            mambuSyncedAt?: string | undefined;
            daysRemaining?: number | undefined;
            paid?: boolean | undefined;
            paidOff?: boolean | undefined;
            daysToNextInstallment?: number | undefined;
            id: number;
            status: string;
            client: {
                location: string;
                id: number;
                status: number;
                fullName: string;
                idNumber: string;
                emailAddress: string;
                phoneNumber: string;
                createdAt: string;
                updatedAt: string;
            };
            createdAt: string;
            updatedAt: string;
            accountId: string;
            firstRepaymentDate: any;
            loanName: string;
            mambuImei: string;
            clientId: number;
            encodedKey: string;
        };
        imei: string;
        createdAt: string;
        updatedAt: string;
        loanId: number;
        clientId: number;
        locked: boolean;
    }[]>;
    saveLockHistory(data: any): Promise<{
        createdAt?: string | undefined;
        updatedAt?: string | undefined;
        lockedAt?: any;
        unlockedAt?: any;
        type: number;
        reason: string;
        id: number;
        device: {
            mambuSynced?: boolean | undefined;
            mambuSyncedAt?: any;
            serialNo?: any;
            make?: any;
            model?: any;
            nuovoSynced?: boolean | undefined;
            nuovoSyncedAt?: any;
            nuovoDeviceId?: any;
            lockReady?: boolean | undefined;
            lockReadyScheduleAt?: any;
            lockDateSynced?: boolean | undefined;
            nextLockDate?: any;
            initialLockDate?: any;
            lastConnectedAt?: any;
            reminderSet?: boolean | undefined;
            reminderSetDate?: any;
            scheduleNumber?: number | undefined;
            id: number;
            status: any;
            client: {
                location: string;
                id: number;
                status: number;
                fullName: string;
                idNumber: string;
                emailAddress: string;
                phoneNumber: string;
                createdAt: string;
                updatedAt: string;
            };
            loan: {
                retry?: number | undefined;
                mambuSynced?: boolean | undefined;
                mambuSyncedAt?: string | undefined;
                daysRemaining?: number | undefined;
                paid?: boolean | undefined;
                paidOff?: boolean | undefined;
                daysToNextInstallment?: number | undefined;
                id: number;
                status: string;
                client: {
                    location: string;
                    id: number;
                    status: number;
                    fullName: string;
                    idNumber: string;
                    emailAddress: string;
                    phoneNumber: string;
                    createdAt: string;
                    updatedAt: string;
                };
                createdAt: string;
                updatedAt: string;
                accountId: string;
                firstRepaymentDate: any;
                loanName: string;
                mambuImei: string;
                clientId: number;
                encodedKey: string;
            };
            imei: string;
            createdAt: string;
            updatedAt: string;
            loanId: number;
            clientId: number;
            locked: boolean;
        };
        loan: {
            retry?: number | undefined;
            mambuSynced?: boolean | undefined;
            mambuSyncedAt?: string | undefined;
            daysRemaining?: number | undefined;
            paid?: boolean | undefined;
            paidOff?: boolean | undefined;
            daysToNextInstallment?: number | undefined;
            id: number;
            status: string;
            client: {
                location: string;
                id: number;
                status: number;
                fullName: string;
                idNumber: string;
                emailAddress: string;
                phoneNumber: string;
                createdAt: string;
                updatedAt: string;
            };
            createdAt: string;
            updatedAt: string;
            accountId: string;
            firstRepaymentDate: any;
            loanName: string;
            mambuImei: string;
            clientId: number;
            encodedKey: string;
        };
        deviceId: number;
        loanId: number;
    }>;
    lockDevice(deviceId: number[]): Promise<any>;
    unlockDevice(deviceId: number[]): Promise<any>;
    updateDevice(devicesId: number[]): void;
    updateOneDevice(deviceId: number, data: any): Promise<{
        mambuSynced?: boolean | undefined;
        mambuSyncedAt?: any;
        serialNo?: any;
        make?: any;
        model?: any;
        nuovoSynced?: boolean | undefined;
        nuovoSyncedAt?: any;
        nuovoDeviceId?: any;
        lockReady?: boolean | undefined;
        lockReadyScheduleAt?: any;
        lockDateSynced?: boolean | undefined;
        nextLockDate?: any;
        initialLockDate?: any;
        lastConnectedAt?: any;
        reminderSet?: boolean | undefined;
        reminderSetDate?: any;
        scheduleNumber?: number | undefined;
        id: number;
        status: any;
        client: {
            location: string;
            id: number;
            status: number;
            fullName: string;
            idNumber: string;
            emailAddress: string;
            phoneNumber: string;
            createdAt: string;
            updatedAt: string;
        };
        loan: {
            retry?: number | undefined;
            mambuSynced?: boolean | undefined;
            mambuSyncedAt?: string | undefined;
            daysRemaining?: number | undefined;
            paid?: boolean | undefined;
            paidOff?: boolean | undefined;
            daysToNextInstallment?: number | undefined;
            id: number;
            status: string;
            client: {
                location: string;
                id: number;
                status: number;
                fullName: string;
                idNumber: string;
                emailAddress: string;
                phoneNumber: string;
                createdAt: string;
                updatedAt: string;
            };
            createdAt: string;
            updatedAt: string;
            accountId: string;
            firstRepaymentDate: any;
            loanName: string;
            mambuImei: string;
            clientId: number;
            encodedKey: string;
        };
        imei: string;
        createdAt: string;
        updatedAt: string;
        loanId: number;
        clientId: number;
        locked: boolean;
    }>;
    applyLock(nuovoDeviceId: number[], devices: Device[], lockType: 'lock' | 'unlock'): void;
}
